server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: "ForoHub"
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://localhost/forohub_api
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
api:
  security:
    secret: ${JWT_SECRET:123456}

